# Generated by Django 3.2.3 on 2021-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_channel',
            field=models.CharField(default='YoutuBe Channel', max_length=250),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='link', max_length=300),
        ),
    ]
