# Generated by Django 3.2.3 on 2021-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20210520_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='youtube_channel',
            field=models.CharField(default='My Channel', max_length=250),
        ),
    ]
