# Generated by Django 3.2.3 on 2021-06-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_rename_insta_link_team_linkdin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='media/team/%Y/%m/'),
        ),
    ]
