# Generated by Django 3.2.4 on 2021-06-05 15:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Head',
        ),
    ]
