# Generated by Django 3.2.3 on 2021-05-26 15:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210523_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('canon', 'canon'), ('nikon', 'nikon'), ('red', 'red'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='catagory',
            field=models.CharField(choices=[('coding', 'coding'), ('mobile', 'mobile'), ('vlog', 'vlog'), ('gaming', 'gaming'), ('fuji', 'fuji'), ('comedy', 'comedy'), ('cooking', 'cooking'), ('sports', 'sports'), ('fashion', 'fashion'), ('motovlog', 'motovlog'), ('film_makers', 'film_making')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=244),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
