# Generated by Django 3.2.4 on 2021-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
